# List of Attribute Mappings for the CartoonSet Dataset https://google.github.io/cartoonset/download.html

# Artwork
chin_length: # Length of chin (below mouth region)
  0: "short"
  1: "medium length"
  2: "long"

eye_angle: # Tilt of the eye inwards or outwards
  0: "tilted inward"
  1: "neutral"
  2: "tilted outward"

eye_lashes: # Whether or not eyelashes are visible
  0: "no"
  1: "visible"

eye_lid: # Appearance of the eyelids
  0: "normal"
  1: "single"

eyebrow_shape: # Shape of eyebrows
  0: "flat"
  1: "slightly curved"
  2: "low arch"
  3: "high arch"
  4: "steep arch"
  5: "thick rounded"
  6: "soft arch"
  7: "straight horizontal"
  8: "short curved"
  9: "rounded thin"
  10: "thin flat"
  11: "straight thin"
  12: "high soft arch"
  13: "textured flat"

eyebrow_weight: # Line weight of eyebrows
  0: "thin line"
  1: "thick line"

face_shape: # Overall shape of the face TODO
  0: "inverted triangle"
  1: "oblong"
  2: "round"
  3: "oval"
  4: "heart"
  5: "diamond"
  6: "square"

facial_hair: # Type of facial hair (type 14 is no hair)
  0: "stubble"
  1: "sideburns"
  2: "full beard"
  3: "full beard thick"
  4: "goatee"
  5: "mustache"
  6: "mustache with goatee"
  7: "mustache with soul patch"
  8: "mustache with chin strap"
  9: "boxed beard"
  10: "circle beard"
  11: "full beard rounded"
  12: "chin curtain"
  13: "goatee patch"
  14: "no"

glasses: # Type of glasses (type 11 is no glasses)
  0: "aviator sunglasses"
  1: "sport dark sunglasses"
  2: "cat eye red frames"
  3: "rectangular thin transparent frames"
  4: "rectangular pink arm transparent frames"
  5: "round white thick frames"
  6: "square grey frames"
  7: "round thick frames"
  8: "cat eye dark sunglasses"
  9: "round sunglasses"
  10: "heart-shaped sunglasses"
  11: "no"

hair: # Type of head hair
  0: "bald"
  1: "shaved" ###
  2: "" ###
  3: "double space buns"
  4: "pigtails"
  5: "afro puff"
  6: "dreadlocks"
  7: "short dreadlocks"
  8: "spiky mohawk" ### 
  9: "curly short bob"
  10: "curly short crop"
  11: "short crop"
  12: "short messy front flip"
  13: "top knot bun"
  14: "wavy medium length"
  15: "short curly afro"
  16: "medium dreadlocks"
  17: "short neat side-part" ###
  18: "short crew cut"
  19: "short buzz"
  20: "bald top with side hair"
  21: "buzz"
  22: "short textured fringe"
  23: "short wavy volume"
  24: "short afro curly"
  25: "shoulder length wavy"
  26: "neck length wavy"
  27: "curly top fade"
  28: "double braids"
  29: "pigtail braids with bangs"
  30: "short curly bob"
  31: "short messy crop"
  32: "short taper"
  33: "shoulder length wavy bob"
  34: "medium wavy length"
  35: "long straight with bun"
  36: "short curly bob with bangs"
  37: "short wavy mess"
  38: "curly afro top"
  39: "short wavy crop"
  40: "long straight with bangs"
  41: "pigtail braids"
  42: "medium long straight"
  43: "spiky faux hawk"
  44: "short stubble crop"
  45: "short neat crop"
  46: "short slicked back"
  47: "long straight layered"
  48: "short side-swept bob"
  49: "short wavy bob"
  50: "spiky hair"
  51: "short side parted"
  52: "short spiky crop"
  53: "short side swept"
  54: "short textured spiky"
  55: "short bun"
  56: "short curly volume"
  57: "long straight"
  58: "straight high ponytail"
  59: "wavy high ponytail"
  60: "shoulder length wavy with side part"
  61: "short neat crop"
  62: "short wavy textured"
  63: "long straight hair"
  64: "high ponytail with bangs"
  65: "medium straight layered"
  66: "short straight crop"
  67: "ear length straight"
  68: "high bun"
  69: "long straight with side part"
  70: "high straight ponytail with side part"
  71: "shoulder length wavy with side part"
  72: "short cropped with side part"
  73: "short messy crop with side part"
  74: "short side part"
  75: "short bob with side part"
  76: "short cropped with bangs"
  77: "spiky textured crop"
  78: "long curly volume"
  79: "shoulder length straight"
  80: "medium wavy volume"
  81: "medium straight bob"
  82: "neck length straight bob"
  83: "short neat crop"
  84: "short neat bun"
  85: "shoulder length wavy"
  86: "shoulder length sleek bob"
  87: "wavy high ponytail"
  88: "neck length wavy bob"
  89: "short cropped wavy"
  90: "medium curly volume"
  91: "short curly bob with side part"
  92: "short wavy crop with side part"
  93: "shoulder length wavy"
  94: "medium wavy bob"
  95: "high wavy ponytail"
  96: "double pigtails"
  97: "afro volume"
  98: "medium textured top"
  99: "short cropped curly"
  100: "long wavy"
  101: "medium volume wavy"
  102: "high wavy ponytail"
  103: "medium curly"
  104: "short curly volume"
  105: "short curly crop"
  106: "high volume wavy"
  107: "short neat crop"
  108: "baby patch"
  109: "baby tuft with bow"
  110: "receding hairline"
  

# Colors
eye_color: # Color of the eye irises
  0: "brown"
  1: "blue"
  2: "green"
  3: "gray"
  4: "black"

face_color: # Color of the face skin TODO
  0: "dark brown"
  1: "medium dark brown"
  2: "medium brown"
  3: "warm tan"
  4: "light tan"
  5: "pale tan"
  6: "fair pinkish"
  7: "fair"
  8: "light beige"
  9: "light peach"
  10: "pale beige"

glasses_color: # Color of the glasses, if present
  0: "black"
  1: "cream"
  2: "blue"
  3: "red"
  4: "gray"
  5: "white"
  6: "pink"

hair_color: # Color of the hair, facial hair, and eyebrows
  0: "blonde"
  1: "yellow"
  2: "orange"
  3: "red"
  4: "light brown"
  5: "brown"
  6: "dark brown"
  7: "black"
  8: "gray"
  9: "white"

# Proportions
eye_eyebrow_distance: # Distance between the eye and eyebrows
  0: "medium distance"
  1: "far"
  2: "close"

eye_slant: # Similar to eye_angle, but rotates the eye and does not change artwork
  0: "slanted up"
  1: "straight"
  2: "slanted down"

eyebrow_thickness: # Vertical scaling of the eyebrows
  0: "thin"
  1: "medium thin"
  2: "medium thick"
  3: "thick"

eyebrow_width: # Horizontal scaling of the eyebrows
  0: "narrow"
  1: "medium width"
  2: "wide"
