# configs/config.yaml

project_name: "pixel-avatar-ddpm"
seed: 42 # For reproducibility

data:
  raw_dataset_10k_path: "data/raw/cartoonset10k"
  raw_dataset_100k_path: "data/raw/cartoonset100k"
  processed_dataset_path: "data/processed/"
  crop_size: 64 # Crop size for removing white borders from images
  image_size: 32 # Image size for training (32x32) or (64x64)

  held_out_combinations:
    - attribute_1: "hair_color"
      value_1: "blue"
      attribute_2: "eye_shape"
      value_2: "round"

model:
  # ResNet Parameters
  resnet_base_channels: 64 # Base number of channels in the ResNet
  resnet_channel_mults: [1, 2, 4] # Spatial resolution multipliers for ResNet layers
  resnet_spatial_resolutions: 2 # Number of spatial resolution levels in the ResNet

  # Time Encoder Parameters
  time_encoder_mult: 4 # Hidden size for the time encoder

  # Text Encoder Parameters
  text_encoder_layers: 3 # Number of layers in the text encoder
  text_hidden_size: 128 # Hidden size for the text encoder

diffusion:
  num_timesteps: 1000
  schedule_type: "linear"
  beta_start: 0.0001
  beta_end: 0.02

training:
  batch_size: 64
  learning_rate: 0.0002
  num_epochs: 100
  checkpoint_dir: "checkpoints/"
